Refactor DB API to hide leaked abstractions
radixdlt/radixdlt pull request #26
Opened 2021-01-20 15:53 UTC by siy

2021-01-20 21:10 UTC, talekhinezh requested changes

2021-01-20 21:10 UTC, talekhinezh commented on radixdlt-core/radixdlt/src/main/java/com/radixdlt/store/berkeley/BerkeleyTransaction.java
> +package com.radixdlt.store.berkeley;
Missing license header

2021-01-20 21:10 UTC, talekhinezh commented on radixdlt-core/radixdlt/src/main/java/com/radixdlt/store/berkeley/BerkeleyTransaction.java
> +public class BerkeleyTransaction implements Transaction {
Missing javadoc description + `final` keyword

2021-01-20 21:10 UTC, talekhinezh commented on radixdlt-core/radixdlt/src/main/java/com/radixdlt/store/berkeley/BerkeleyTransaction.java
> +public class BerkeleyTransaction implements Transaction {
Also seems like this class can be package private

2021-01-20 21:10 UTC, talekhinezh commented on radixdlt-core/radixdlt/src/main/java/com/radixdlt/store/Transaction.java
> +public interface Transaction {
Missing class description javadoc

2021-01-21 12:53 UTC, clstrfsck approved these changes

2021-01-21 16:08 UTC, talekhinezh approved these changes

2021-01-22 13:06 UTC, merged